"""Cross-attack generalization: train CM on one attack, test on others.

Shows whether a CM trained on attack A generalizes to unseen attacks B, C...
No ASVspoof needed — clones are generated by the attack zoo.

Usage:
    # train on XTTS, test on (whatever else is installed) + baselines
    python -m voice_defense.scripts.run_cross_attack \
        --attacks xtts,openvoice,synthetic_tts,artifact_vc \
        --seen xtts --speakers 10 --epochs 20 --device cuda

    # guaranteed-runnable demo (no external model installs):
    python -m voice_defense.scripts.run_cross_attack \
        --attacks synthetic_tts,artifact_vc --seen synthetic_tts --device cpu

Generators that aren't installed are skipped automatically; synthetic_tts and
artifact_vc always work.
"""

import argparse
import logging

from ..common.compat import apply_all_patches
apply_all_patches()

from ..attack.clone.clone_multi import generate_clones_for_attacks
from ..pipeline.cross_attack import run_cross_attack_eval

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger(__name__)


def main():
    p = argparse.ArgumentParser(description="Cross-attack generalization eval")
    p.add_argument("--attacks", required=True,
                   help="comma-separated generators (e.g. xtts,openvoice,synthetic_tts,artifact_vc)")
    p.add_argument("--seen", required=True, help="generator to TRAIN the CM on")
    p.add_argument("--data-root", default="./data")
    p.add_argument("--output-root", default="./outputs")
    p.add_argument("--speakers", type=int, default=10)
    p.add_argument("--ref-duration", type=int, default=10)
    p.add_argument("--model-type", default="lcnn", choices=["lcnn", "rawnet2"])
    p.add_argument("--epochs", type=int, default=20)
    p.add_argument("--cm-threshold", type=float, default=None,
                   help="CM decision threshold. Default: auto-calibrate on the seen attack.")
    p.add_argument("--device", default="cuda")
    args = p.parse_args()

    attacks = [a.strip() for a in args.attacks.split(",") if a.strip()]
    if args.seen not in attacks:
        attacks = [args.seen] + attacks  # ensure seen is generated

    logger.info("=" * 60)
    logger.info("CROSS-ATTACK: train on '%s', test on %s", args.seen, attacks)
    logger.info("=" * 60)

    per_attack = generate_clones_for_attacks(
        attack_names=attacks, data_root=args.data_root, output_root=args.output_root,
        num_target_speakers=args.speakers, ref_duration=args.ref_duration, device=args.device,
    )

    if args.seen not in per_attack:
        logger.error("Seen attack '%s' was not available — cannot train CM. Available: %s",
                     args.seen, list(per_attack))
        return

    report = run_cross_attack_eval(
        per_attack=per_attack, seen_attack=args.seen, output_root=args.output_root,
        model_type=args.model_type, epochs=args.epochs,
        cm_threshold=args.cm_threshold, device=args.device,
    )

    logger.info("=" * 60)
    logger.info("결과:")
    for r in report["per_attack"]:
        tag = "seen " if r["seen"] else "unseen"
        det = "N/A" if r["detection_rate"] is None else f"{r['detection_rate']*100:.1f}%"
        logger.info("  [%s] %-14s 탐지율=%s (n=%d)", tag, r["attack"], det, r["n_clones"])
    logger.info("리포트: %s/results/cross_attack_report.md", args.output_root)
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
